### ISSUE TITLE
Re-using modules across different sims

### ISSUE THREAD

**Issue by robynstuart** [starsimhub/starsim#103]
Let's say I want to compare two gonorrhea sims, one with HIV and one without. First I make the people and diseases:

```
ppl = ss.People(10000)
ppl.networks = ss.ndict(ss.simple_sexual())

gon = ss.Gonorrhea()
gon.pars['beta'] = {'simple_sexual': [0.02, 0.01]}

hiv = ss.HIV()
hiv.pars['beta'] = {'simple_sexual': [0.0008, 0.0004]}
```

It feels intuitive to make the sims like:
```
sim1 = ss.Sim(people=ppl, modules=gon)
sim1.run()

sim2 = ss.Sim(people=ppl, modules=[hiv, gon])
sim2.run()
```

but I can't do this, because the people were initialized the first time I used them in a sim. What's the best way?

**Comment by cliffckerr** [comment]
I think the right solution is to ensure all objects have a `.copy()` method. Then this would look like:
```py
sim1 = ss.Sim(people=ppl.copy(), modules=gon.copy())
sim1.run()

sim2 = ss.Sim(people=ppl.copy(), modules=[hiv, gon])
sim2.run()
```

**Comment by robynstuart** [comment]
@cliffckerr why is that better than `copy_inputs=True`? Requiring users to do the copy() when feeding in inputs doesn't feel very intuitive to me

**Comment by cliffckerr** [comment]
@robynstuart what about both? In fact maybe `copy_inputs` could call objects' `.copy()` methods ...

**Comment by robynstuart** [comment]
Yeah that'd work from my perspective, although I'm mindful of @RHull-IDM's comment that other users may have a different framework of reference for how copied items are used. My own frame of reference comes from an admittedly basic understanding of the "scope" of a sim. I think of each sim as its own self-contained environment, which is why I would have expected the initial example provided in this issue to work.

**Comment by RHull-IDM** [comment]
This option `sim1 = ss.Sim(people=ppl.copy(), modules=gon.copy())` is also potentially confusing because you have to do it on the original object. e.g. you can't do
```python
sim1 = ss.Sim(people=ppl, modules=gon)
sim1.run()
sim2 = ss.Sim(people=ppl.copy(), modules=gon.copy())
sim2.run()
``` 
you have to use copies in both or use the copied versions first. You can use the original object in the final sim but the first sim and all subsequent other than the last must also be copies. 

I really like an AlreadyRun error (or at least warning?) for any object that maintains its own state, but how would that work? Would we check for something in Sim's `__init__()`?

**Comment by cliffckerr** [comment]
Subsumed into #301
