### ISSUE TITLE
Rethink levels of inheritance

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#439]
Modularity and reuse is good, right? Except it can get really confusing to figure out what is and isn't defined. Even for SIR, we have `Module → Disease → Infection → SIR`, with each one doing meaningful work. Pars and states and methods get seamlessly merged, which is great, but makes it quite opaque what's going on under the hood (an example was @jamiecohen's attempt to define a `rel_sus` property for HPV, which conflicted with a built-in `Infection` attribute).

Proposal: be more explicit about what is being called and initialized where. Specifically:
- [x] Each class should be self-contained in defining its own states, not relying on a deep stack of `super().__init__()` calls.
- [x] Method calls should be explicit, e.g. each class should define each critical method, even if it just calls a parent method (e.g. `def make_new_cases(self, sim): super().make_new_cases(sim)`)
- [x] Rethink `sim.step()` logic and if anything can be combined/simplified; likewise for disease methods
- [x] Think about if the sim can just be stored in each module, so it doesn't have to get passed around all the time

**Comment by RomeshA** [comment]
Another option to consider could be to incorporate more of a Mixin architecture/co-operative multiple inheritance, in that paradigm it is less about a deep tree of inheritance, and more about bringing together features.

Personally I'd quite like to see (or at least try out) class variables making a re-appearance as a means of doing things like declaring which states and parameters are defined by a particular class, that way you can easily see them upfront rather than having to dig through `__init__()` methods

**Comment by daniel-klein** [comment]
Keen for iteration here as I agree it can be particularly confusing for new (and experienced!) developers alike. I like the mixin approach @RomeshA suggests as having each class own and define its own states will be quite a challenging shift from the current approach, if I understand correctly. A good place to start might be with Networks, where we have SexualNetwork and DynamicNetwork that could be mixed in?

**Comment by cliffckerr** [comment]
Closed by #612
