### ISSUE TITLE
Review and simplify run.py - overlapping functions

### ISSUE THREAD

**Issue by kaa2102** [starsimhub/starsim#454]
run.py has class MultiSim with redundant functions: single_run(), multi_run(), and parellel() that have very similar functionality.

https://github.com/starsimhub/starsim/blob/main/starsim/run.py

```
class MultiSim(sc.prettyobj):
        return self.reduce(use_mean=False, quantiles=quantiles, **kwargs)


def single_run(sim, ind=0, reseed=True, keep_people=False, run_args=None, sim_args=None,
    return sim


def multi_run(sim, n_runs=4, reseed=None, iterpars=None, keep_people=None, run_args=None, sim_args=None,
    return sims


def parallel(*args, **kwargs):
    return MultiSim(sims=sims).run(**kwargs)
```

**Comment by kaa2102** [comment]
[MultiSim class is called and runs multi_run() function in run.py](https://github.com/starsimhub/starsim/blob/ae4f4a92b268d19e86cc80f9f53e93b53fcc5698/tests/test_simple.py#L149)

I don't see how parallel() and single_run() functions would be called from MultiSim class.

**Comment by cliffckerr** [comment]
We could refactor these, but they're not overlapping in the sense of providing comparable functionality. `single_run()` is the function that actually gets run in parallel. `multi_run()` is a wrapper to call `single_run()` with `sc.parallelize()`. `MultiSim.run()` calls `multi_run()` with arguments based on the `MultiSim` attributes. and `parallel()` is a shortcut to the most common use case, which is just running a list of sims in parallel.

I think we need to keep `single_run()` and `parallel()`, but we could potentially merge the functionality of `multi_run()` into `MultiSim.run()` since `multi_run` isn't used anywhere else.

**Comment by cliffckerr** [comment]
Actually, once we add the Scenarios class, `multi_run` will be used in two places I believe, so good to have separate.
