### ISSUE TITLE
Inplace arithmetic fails

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#502]
Causes a segfault (!):
```py
import starsim as ss

def jump_age(sim):
    """ Arbitrary intervention to reduce people's ages in the simulation """
    if sim.ti == 20:
        sim.people.age += 1000 # sim.people.age = sim.people.age + 1000 works

sim = ss.Sim(interventions=jump_age)
sim.run()
```

**Comment by kaa2102** [comment]
The inplace arithmetic works well in Python but numpy arrays get mutated by " += ".

https://stackoverflow.com/questions/35910577/why-does-python-numpys-mutate-the-original-array

**Comment by devclinton** [comment]
@cliffckerr - I spent an hour today looking at this and have a root cause identified.

We can boil it down to the following case

```python
x = Arr([1,2,3])
x += 1000
```

This replicates the segfault


It appears what is happening it  __iadd__(=+) call ufunc with add, and kwargs out out=(self). This means the out Kwarg is of type FloatArr in this case. This ends up in a infinite recursion somehow, maybe repeated called to add on the out kwargs?

 If I add the following code to the Arr.__array_ufunc__ before the return, things work fine

```python
        # Handle the 'out' parameter in kwargs
        if 'out' in kwargs:
            out = kwargs['out']
            if isinstance(out, tuple):
                kwargs['out'] = tuple(x.values if isinstance(x, Arr) else x for x in out)
            elif isinstance(out, Arr):
                kwargs['out'] = out.values
```

This makes some sense looking here https://numpy.org/doc/stable/user/basics.subclassing.html#array-ufunc-for-ufuncs 

I am not sure if we want to do a more extensive fix like and look at other parameters and situations this could arise. I also know some others things are in flux so not sure if this already being addressed somewhere else.

**Comment by devclinton** [comment]
This version adapted from the numpy example seems to work for all our tests

```python
 def __array_ufunc__(self, ufunc, method, *inputs, out=None, **kwargs): 
        args = []
        in_no = []
        for i, input_ in enumerate(inputs):
            if isinstance(input_, Arr):
                in_no.append(i)
                args.append(input_.values)
            else:
                args.append(input_)

        outputs = out
        out_no = []
        if outputs:
            out_args = []
            for j, output in enumerate(outputs):
                if isinstance(output, Arr):
                    out_no.append(j)
                    out_args.append(output.values)
                else:
                    out_args.append(output)
            kwargs['out'] = tuple(out_args)
        else:
            outputs = (None,) * ufunc.nout

        info = {}
        if in_no:
            info['inputs'] = in_no
        if out_no:
            info['outputs'] = out_no

        results = self.values.__array_ufunc__(ufunc, method, *args, **kwargs)
        if results is NotImplemented:
            return NotImplemented

        if method == 'at':
            if isinstance(inputs[0], Arr):
                inputs[0].info = info
            return

        if ufunc.nout == 1:
            results = (results,)

        results = tuple((np.asarray(result)
                         if output is None else output)
                        for result, output in zip(results, outputs))
        if results and isinstance(results[0], Arr):
            results[0].info = info

        return results[0] if len(results) == 1 else results
```

**Comment by cliffckerr** [comment]
@RomeshA what do you think the right behavior here would be? Logically I'd assume that `FloatArr += 1` should return a `FloatArr`, but if it has to cast to a (plain) NumPy array and back that could be slow (...or not?)...
